version: "3.8"

services:
  postgresql:
    container_name: postgresql
    build: postgresql
    image: text-analyzer-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    command: postgres
